# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.home-assistant.io
title: Home Assistant
subtitle: Open source home automation that puts local control and privacy first.
author: Home Assistant
simple_search: https://www.google.com/search
description: >-
  Open source home automation that puts local control and privacy first.
  Powered by a worldwide community of tinkerers and DIY enthusiasts.
  Perfect to run on a Raspberry Pi or a local server.

date_format: "ordinal"

# RSS / Email (optional) subscription links
subscribe_rss: /atom.xml
subscribe_email: ""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:title/
source: source
destination: public/
plugins_dir: plugins
code_dir: downloads/code
category_dir: blog/categories

markdown: CommonMark
timezone: UTC
liquid:
  error_mode: strict

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

highlighter: none

plugins:
  - jekyll-toc

paginate: 10
paginate_path: "blog/page:num"
recent_posts: 5
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!--more-->"

titlecase: true

# Each layout uses the default asides, but they can have their own asides instead.
# blog_index_asides:
# post_asides:
# page_asides:

collections:
  integrations:
    output: true
  docs:
    output: true
  addons:
    output: true
  faq:
    output: true
  dashboards:
    output: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Search
algolia:
  api_key: ""

# Twitter
twitter_user: balloob
twitter_tweet_button: true

# Facebook Like
facebook_like: true

social:
  visible: false
  facebook:
    app_id: 338291289691179

  twitter:
    account: home_assistant

  mastodon:
    account: "https://fosstodon.org/@homeassistant"

# Home Assistant release details
current_major_version: 2024
current_minor_version: 10
current_patch_version: 1
date_released: 2024-10-04

# Front matter defaults
defaults:
  # Defaults for all pages
  - scope:
      path: ""
    values:
      layout: page
      comments: false
      footer: true
      sharing: true
      sidebar: true
      featured: false

  # Defaults for blogs posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      footer: true
      sharing: true
      sidebar: true
      toc: true

  # Enable table of contents
  - scope:
      path: ""
      type: [dashboards, integrations, docs, installation, common-tasks, getting-started, more-info, voice_control, hassio]
    values:
      toc: true

  # Remove some resources from sitemap
  - scope:
      path: "google*.html"
    values:
      sitemap: false

  - scope:
      path: "static/fonts/**/*.html"
    values:
      sitemap: false

  - scope:
      path: "static/mdi-demo.html"
    values:
      sitemap: false

  - scope:
      path: "blueprints/**/*.yaml"
    values:
      render_with_liquid: false
      layout: none

# Support for files Jekyll will normally exclude
include:
  - "_headers"
  - "_redirects"
  - ".well-known"

# Table of contents
toc:
  min_level: 2
  max_level: 3

# Configuration for installation pages
installation:
  container: "ghcr.io/home-assistant/home-assistant"
  versions:
    python: "3.12"
  types:
    odroid:
      board: ODROID
      installation_media: "eMMC module or SD card"
      variants:
        - name: "ODROID-N2"
          key: "odroid-n2"
        - name: "ODROID-N2+"
          key: "odroid-n2"
        - name: "ODROID-C2"
          key: "odroid-c2"
        - name: "ODROID-C4"
          key: "odroid-c4"
        - name: "ODROID-M1"
          key: "odroid-m1"
        - name: "ODROID-M1S"
          key: "odroid-m1s"

    raspberrypi:
      board: Raspberry Pi
      installation_media: "SD card"
      variants:
        - name: "Raspberry Pi 5"
          key: "rpi5-64"
        - name: "Raspberry Pi 4"
          key: "rpi4-64"
        - name: "Raspberry Pi 3"
          key: "rpi3-64"

    generic-x86-64:
      board: Generic x86-64
      installation_media: "storage device"
      variants:
        - name: "Generic x86-64"
          key: "generic-x86-64"
